name: Windows Build
on: [push]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Blahjack
      run: |
        @call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        cl /EHsc main.cpp /link /out:blahjack.exe
      shell: cmd